const express = require("express");
const router = express.Router();
const foodController = require("../controllers/foodController");
const userController = require("../controllers/userController");
const eateryController = require("../controllers/eateryController");
const shipperController = require("../controllers/shipperController");
const cartController = require("../controllers/cartController");
// router.get("/", foodController.getAllFoods);
router.get("/getAllFoodOfEatery", foodController.getAllFoodOfEatery);
router.post("/login", userController.login);
router.post("/addEatery", eateryController.addEatery);
router.post("/addFavoriteEatery", eateryController.addFavoriteEatery);
router.get("/getAllEatery", eateryController.getAllEatery);
router.get("/getUserInfor", userController.getUserInfor);
router.get("/getAllFavoriteEatery", eateryController.getAllFavoriteEatery);
router.get("/getAvailableShipper", shipperController.getAvailableShipper);
router.post("/setShipperAvailable", shipperController.setShipperAvailable);
router.post("/addToCart", cartController.addToCart);
router.post("/getCartByUserId", cartController.getCartByUserId);
router.post("/getEateryCoordinates", eateryController.getEateryCoordinates);
module.exports = router;
